Add vecOfSelfAsPtr method
chinedufn/swift-bridge pull request #216
Opened 2023-04-24 17:42 UTC by aiongg

I followed the general outline provided in issue #214. However, it seems that we cannot use `Self` directly, because some types that implement `Vectorizable` (like `RustString`) would not actually be returning a pointer to `Self`, but rather to an element in the `RustVec`. Therefore I had to add a new `associatedtype Elem`, which is normally just `= T` (the type being stored in the `RustVec`, but can be different where required.

The added test passes, and I have built my own project against this branch and indeed it works there as well.

For reference:

https://github.com/aiongg/khiin-rs/blob/swift-bridge/swift/Keyboard/KeyboardViewController.swift#L78-L92

Line 91 here is using the `as_ptr()` method, which works perfectly for constructing a `Data` object.

And my bridge module code is now reduced to 1 line, as expected (well 2, if you count dereferencing the pointer):

https://github.com/aiongg/khiin-rs/blob/swift-bridge/swift/bridge/src/lib.rs#L41-L49

2023-04-24 17:47 UTC, aiongg commented on SwiftRustIntegrationTestRunner/SwiftRustIntegrationTestRunnerTests/VecTests.swift
> +    }
Basic test as described in the issue.

2023-04-24 17:48 UTC, aiongg commented on crates/swift-bridge-build/src/generate_core.rs
> +
Add the new `typealias` up top, and below the method implementation - it's the same procedure for all of these generated code segments.

2023-04-24 17:50 UTC, aiongg commented on crates/swift-bridge-build/src/generate_core/rust_string.swift
> +
Special handling for `RustString`, which takes a `UInt8` type parameter instead of the usual `Self`.

2023-04-24 17:52 UTC, aiongg commented on crates/swift-bridge-build/src/generate_core/rust_vec.swift
>      associatedtype SelfRefMut
The new `associatedtype Elem` for the `Vectorizable` protocol

2023-04-26 08:33 UTC, chinedufn requested changes
`.as_ptr()` for a `RustVec<RustString>` should not return an `UnsafePointer<UInt8>`, but rather an `UnsafePointer<RustStringRef>`.

Consider the following Rust code:

```rust
let strings: Vec<String> = vec![];
let ptr: *const String = strings.as_ptr();
```

`Vec<String>.as_ptr()` returns a `*const String`.

Maybe you were accidentally looking at `String.as_ptr()`, which is unrelated to this PR.

---

So, I think we can remove the `Elem` associated type and instead just have the existing `SelfRef` associated type https://github.com/chinedufn/swift-bridge/blob/53ab502791dcc22f755524c91f01dd6c61d5dfb1/crates/swift-bridge-build/src/generate_core/rust_vec.swift#L95 , which from `RustVec<RustString>` is a `RustStringRef` https://github.com/chinedufn/swift-bridge/blob/53ab502791dcc22f755524c91f01dd6c61d5dfb1/crates/swift-bridge-build/src/generate_core/rust_string.swift#L72

2023-04-26 09:24 UTC, aiongg commented
Ok great I'll try it. I think I tried that the first time and encountered some issue, but if you think it should work then I must have done something wrong so I'll try again and update the PR if it works.

2023-04-26 09:33 UTC, chinedufn commented
Mmm I'm not certain but it seems directionally correct. Let me know if you run into an issue.

2023-04-26 12:48 UTC, aiongg commented
@chinedufn you were right, I was confusing `RustString` with `RustVec<RustString>`. Works fine with `SelfRef` as you described. Makes more sense now, too. I guess that's what I get for trying to do it at 2am last time 😅

2023-04-26 14:03 UTC, chinedufn commented
Thanks looks good.

All that's missing is to update your PR body with quick example code showing of what this PR now enables.

Here's an example from another PR that you can use as inspiration https://github.com/chinedufn/swift-bridge/pull/189

These examples get used in our release notes, and they help folks that are looking at old PRs understand exactly what the PR does.

Once you add an example (and perhaps clean up the info in your PR body that is no longer true) we can merge this!

2023-04-26 14:56 UTC, aiongg commented
@chinedufn done, please review.

2023-04-26 15:41 UTC, merged